### ISSUE TITLE
about the variable pos : not initiated 

### ISSUE THREAD

**Issue by BioWu** [mahulchak/mscaffolder#1]
Hi, when building this program. One warning occurred :
```
scflib.cpp:217:57: warning: 'pos' may be used uninitialized in this function [-Wmaybe-uninitialized]
      tempname = refName + merge.qStoreStart[refName][pos]; //find the index corresponding to the query
```
I wonder whether this problem will lead any bad effect?

**Comment by mahulchak** [comment]
It should not

From: WuChangCheng
Sent: Monday, January 8, 2018 7:29 PM
To: mahulchak/mscaffolder
Cc: Subscribed
Subject: [mahulchak/mscaffolder] about the variable pos : not initiated (#1)

Hi, when building this program. One warning occurred :
scflib.cpp:217:57: warning: 'pos' may be used uninitialized in this function [-Wmaybe-uninitialized]
      tempname = refName + merge.qStoreStart[refName][pos]; //find the index corresponding to the query
I wonder whether this problem will lead any bad effect?
